version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    image: sport-linker-be:1.0.0
    restart: always
    networks:
      - backend

  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - backend

  redis: 
    image: redis:6.2
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
