version: '3'

services:

  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data_sportlinker:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: mysql-container
    networks:
      - backend


  redis: 
    image: redis:6.2
    volumes:
      - redis_data_sportlinker:/data
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    image: sport-linker-be:1.0.0
    depends_on:
      - mysql
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data_sportlinker:
  redis_data_sportlinker:
