version: '3'

services:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - sportlinker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis: 
    image: redis:6.2
    volumes:
      - redis:/data
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - sportlinker
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    image: sport-linker-be:1.0.0
    depends_on:
      mysql: 
        condition: service_healthy
    networks:
      - sportlinker
    command: 
      - /bin/sh
      - -c
      - |
        npx prisma generate
        npx prisma db push

networks:
  sportlinker:
    driver: bridge

volumes:
  mysql:
  redis:
